const bookingTables = {
    bookings: {
        uniqueId:"UniqueID",
        bookedBy:"BookedBy",
        source:"Source",
        paymentMethod:"PaymentMethod",
        isChannelBooking:"IsChannelBooking",
        subBookingId:"SubBookingId",
        transaction_id:"TransactionId",
        property_id:"property_id",
        guest_id:"guest_id",
        createDatetime:"Createdatetime",
        modifyDatetime:"Modifydatetime",
        status:"Status",
        isConfirmed:"IsConfirmed",
        currentStatus:"CurrentStatus",
        voucherNo:"VoucherNo",
        packageCode:"PackageCode",
        packageName:"PackageName",
        rateplanCode:"RateplanCode",
        rateplanName:"RateplanName",
        eZeePMSRoomid:"",
        roomTypeCode:"RoomTypeCode",
        roomTypeName:"RoomTypeName",
        roomId:"RoomID",
        roomName:"RoomName",
        start:"Start",
        end:"End",
        comment:"Comment",
        affiliateName:"AffiliateName",
        affiliateCode:"AffiliateCode",
        lastOperation:"operation",
        arrivalTime:"ArrivalTime",
        departureTime:"DepartureTime"
    },
    booking_transactions:{
        subBookingId:"SubBookingId",
        transaction_id:"TransactionId",
        createDatetime:"Createdatetime",
        modifyDatetime:"Modifydatetime",
        status:"Status",
        isConfirmed:"IsConfirmed",
        currentStatus:"CurrentStatus",
        voucherNo:"VoucherNo",
        packageCode:"PackageCode",
        packageName:"PackageName",
        rateplanCode:"RateplanCode",
        rateplanName:"RateplanName",
        eZeePMSRoomid:"",
        roomTypeCode:"RoomTypeCode",
        roomTypeName:"RoomTypeName",
        roomId:"RoomID",
        roomName:"RoomName",
        start:"Start",
        end:"End",
        arrivalTime:"ArrivalTime",
        departureTime:"DepartureTime"
    },
    booking_taxes:{
        taxCode:"TaxCode",
        taxName:"TaxName",
        taxAmount:"TaxAmount"
    },
    booking_payments:{
        amount:"amount",
        datetime:"datetime",
        method:"method"
    },
    booking_rentalinfo:{
        effectiveDate:"EffectiveDate",
        adult:"Adult",
        child:"Child",
        rent:"Rent",
        rentPreTax:"RentPreTax",
        discount:"Discount"
    },
    booking_registrations:{
        registrationNo:"RegistrationNo",
        identiyType:"IdentiyType",
        identityNo:"IdentityNo",
        expiryDate:"ExpiryDate"
    },
    booking_tariffs:{
        currencyCode:"CurrencyCode",
        totalAmountAfterTax:"TotalAmountAfterTax",
        totalAmountBeforeTax:"TotalAmountBeforeTax",
        totalTax:"TotalTax",
        totalDiscount:"TotalDiscount",
        totalExtraCharge:"TotalExtraCharge",
        totalPayment:"TotalPayment",
        taCommision:"TACommision"
    },
    pickup_drop:{
        vehicle:"Vehicle",
        pickupDate:"PickupDate",
        pickupTime:"PickupTime",
    }
};
const transactionTables = {
    booking_taxes:{
        type:"multiple",
        tableName:"booking_taxes",
        logElement:"TaxDeatil"
    },
    booking_payments:{
        type:"multiple",
        tableName:"booking_payments",
        logElement:"PaymentDetail"
    },
    booking_rentalinfo:{
        type:"multiple",
        tableName:"booking_rentalinfo",
        logElement:"RentalInfo"
    },
    booking_registrations:{
        type:"single",
        tableName:"booking_registrations",
        logElement:"bookingTran"
    },
    booking_tariffs:{
        type:"single",
        tableName:"booking_tariffs",
        logElement:"bookingTran"
    },
    pickup_drop:{
        type:"single",
        tableName:"pickup_drop",
        logElement:"bookingTran"
    }
};
const userFields = {
    salutation:"Salutation",
    firstname:"FirstName",
    lastname:"LastName",
    //gender:"Gender",
    date_of_birth:"DateOfBirth",
    //spouseDateOfBirth:"SpouseDateOfBirth",
    //weddingAnniversary:"WeddingAnniversary",
    address_line_1:"Address",
    city:"City",
    state:"State",
    //nationality:"Nationality",
    postcode:"Zipcode"
};
module.exports = {bookingTables,transactionTables,userFields};